//3D模型配置
export default 
[
    {
        id:10000,
        nameCn:'飞碟',
        nameEn:'UFO',
        head_url:'/static/3d-models/images/ufo.png',
        model_url:'/static/3d-models/glbs/ufo.glb',
        center:{x:0,y:0},
        scale:100,
        use:[],
        entity:null
    },
    {
        id:10003,
        nameCn:'消防站',
        nameEn:'fire_station',
        head_url:'/static/3d-models/images/fire_station.png',
        model_url:'/static/3d-models/glbs/fire_station.glb',
        center:{x:0,y:0},
        scale:9.5,
        use:[],
        entity:null
    },
    {
        id:10004,
        nameCn:'便利店',
        nameEn:'convenience_store',
        head_url:'/static/3d-models/images/convenience_store.png',
        model_url:'/static/3d-models/glbs/convenience_store.glb',
        center:{x:0,y:0},
        scale:8,
        use:[],
        entity:null
    },
    {
        id:10005,
        nameCn:'法院',
        nameEn:'courthouse',
        head_url:'/static/3d-models/images/courthouse.png',
        model_url:'/static/3d-models/glbs/courthouse.glb',
        center:{x:0,y:0},
        scale:9,
        use:[],
        entity:null
    },
    {
        id:10006,
        nameCn:'工厂',
        nameEn:'factory',
        head_url:'/static/3d-models/images/factory.png',
        model_url:'/static/3d-models/glbs/factory.glb',
        center:{x:0,y:0},
        scale:10,
        use:[],
        entity:null
    },
    {
        id:10007,
        nameCn:'乔治之家',
        nameEn:'home',
        head_url:'/static/3d-models/images/home.png',
        model_url:'/static/3d-models/glbs/home.glb',
        center:{x:0,y:0},
        scale:60,
        use:[],
        entity:null
    },
    {
        id:10008,
        nameCn:'大医院',
        nameEn:'large_hospital',
        head_url:'/static/3d-models/images/large_hospital.png',
        model_url:'/static/3d-models/glbs/large_hospital.glb',
        center:{x:0,y:0},
        scale:10,
        use:[],
        entity:null
    },
    {
        id:10012,
        nameCn:'多层学校',
        nameEn:'multi_story_school',
        head_url:'/static/3d-models/images/multi_story_school.png',
        model_url:'/static/3d-models/glbs/multi_story_school.glb',
        center:{x:0,y:0},
        scale:10,
        use:[],
        entity:null
    },
    {
        id:10013,
        nameCn:'办公楼',
        nameEn:'office',
        head_url:'/static/3d-models/images/office.png',
        model_url:'/static/3d-models/glbs/office.glb',
        center:{x:0,y:0},
        scale:10,
        use:[],
        entity:null
    },
    {
        id:10014,
        nameCn:'警察局',
        nameEn:'police_station',
        head_url:'/static/3d-models/images/police_station.png',
        model_url:'/static/3d-models/glbs/police_station.glb',
        center:{x:0,y:0},
        scale:10,
        use:[],
        entity:null
    },
    {
        id:10015,
        nameCn:'仓库',
        nameEn:'warehouse',
        head_url:'/static/3d-models/images/warehouse.png',
        model_url:'/static/3d-models/glbs/warehouse.glb',
        center:{x:0,y:0},
        scale:10,
        use:[],
        entity:null
    },
    {
        id:10018,
        nameCn:'小城市建筑Ⅰ型',
        nameEn:'small_city_building_1',
        head_url:'/static/3d-models/images/small_city_building_1.png',
        model_url:'/static/3d-models/glbs/small_city_building_1.glb',
        center:{x:0,y:0},
        scale:10,
        use:[],
        entity:null
    },
    {
        id:10019,
        nameCn:'小城市建筑Ⅱ型',
        nameEn:'small_city_building_2',
        head_url:'/static/3d-models/images/small_city_building_2.png',
        model_url:'/static/3d-models/glbs/small_city_building_2.glb',
        center:{x:0,y:0},
        scale:1350,
        use:[],
        entity:null
    },
    {
        id:10020,
        nameCn:'体育场',
        nameEn:'sports_stadium',
        head_url:'/static/3d-models/images/sports_stadium.png',
        model_url:'/static/3d-models/glbs/sports_stadium.glb',
        center:{x:0,y:0},
        scale:5,
        use:[],
        entity:null
    }
]
/*
export default 
[
    {
        id:10000,
        nameCn:'飞碟',
        nameEn:'UFO',
        head_url:'/static/3d-models/images/ufo.png',
        model_url:'/static/3d-models/glbs/ufo.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10001,
        nameCn:'国会大厦',
        nameEn:'capitol',
        head_url:'/static/3d-models/images/capitol.png',
        model_url:'/static/3d-models/glbs/capitol.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10002,
        nameCn:'公主城堡',
        nameEn:'castle',
        head_url:'/static/3d-models/images/castle.png',
        model_url:'/static/3d-models/glbs/castle.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10003,
        nameCn:'消防站',
        nameEn:'fire_station',
        head_url:'/static/3d-models/images/fire_station.png',
        model_url:'/static/3d-models/glbs/fire_station.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10004,
        nameCn:'便利店',
        nameEn:'convenience_store',
        head_url:'/static/3d-models/images/convenience_store.png',
        model_url:'/static/3d-models/glbs/convenience_store.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10005,
        nameCn:'法院',
        nameEn:'courthouse',
        head_url:'/static/3d-models/images/courthouse.png',
        model_url:'/static/3d-models/glbs/courthouse.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10006,
        nameCn:'工厂',
        nameEn:'factory',
        head_url:'/static/3d-models/images/factory.png',
        model_url:'/static/3d-models/glbs/factory.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10007,
        nameCn:'乔治之家',
        nameEn:'home',
        head_url:'/static/3d-models/images/home.png',
        model_url:'/static/3d-models/glbs/home.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10008,
        nameCn:'大医院',
        nameEn:'large_hospital',
        head_url:'/static/3d-models/images/large_hospital.png',
        model_url:'/static/3d-models/glbs/large_hospital.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10009,
        nameCn:'中型摩天大楼Ⅰ型',
        nameEn:'mid_size_skyscrapers_1',
        head_url:'/static/3d-models/images/mid_size_skyscrapers_1.png',
        model_url:'/static/3d-models/glbs/mid_size_skyscrapers_1.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10010,
        nameCn:'中型摩天大楼Ⅱ型',
        nameEn:'mid_size_skyscrapers_2',
        head_url:'/static/3d-models/images/mid_size_skyscrapers_2.png',
        model_url:'/static/3d-models/glbs/mid_size_skyscrapers_2.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10011,
        nameCn:'中型摩天大楼Ⅲ型',
        nameEn:'mid_size_skyscrapers_3',
        head_url:'/static/3d-models/images/mid_size_skyscrapers_3.png',
        model_url:'/static/3d-models/glbs/mid_size_skyscrapers_3.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10012,
        nameCn:'多层学校',
        nameEn:'multi_story_school',
        head_url:'/static/3d-models/images/multi_story_school.png',
        model_url:'/static/3d-models/glbs/multi_story_school.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10013,
        nameCn:'办公楼',
        nameEn:'office',
        head_url:'/static/3d-models/images/office.png',
        model_url:'/static/3d-models/glbs/office.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10014,
        nameCn:'警察局',
        nameEn:'police_station',
        head_url:'/static/3d-models/images/police_station.png',
        model_url:'/static/3d-models/glbs/police_station.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10015,
        nameCn:'仓库',
        nameEn:'warehouse',
        head_url:'/static/3d-models/images/warehouse.png',
        model_url:'/static/3d-models/glbs/warehouse.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10016,
        nameCn:'居住房屋',
        nameEn:'residential_building',
        head_url:'/static/3d-models/images/residential_building.png',
        model_url:'/static/3d-models/glbs/residential_building.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10017,
        nameCn:'住宅',
        nameEn:'residential_house',
        head_url:'/static/3d-models/images/residential_house.png',
        model_url:'/static/3d-models/glbs/residential_house.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10018,
        nameCn:'小城市建筑Ⅰ型',
        nameEn:'small_city_building_1',
        head_url:'/static/3d-models/images/small_city_building_1.png',
        model_url:'/static/3d-models/glbs/small_city_building_1.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10019,
        nameCn:'小城市建筑Ⅱ型',
        nameEn:'small_city_building_2',
        head_url:'/static/3d-models/images/small_city_building_2.png',
        model_url:'/static/3d-models/glbs/small_city_building_2.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10020,
        nameCn:'体育场',
        nameEn:'sports_stadium',
        head_url:'/static/3d-models/images/sports_stadium.png',
        model_url:'/static/3d-models/glbs/sports_stadium.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10021,
        nameCn:'摩天大楼Ⅰ型',
        nameEn:'tall_skyscrapers_1',
        head_url:'/static/3d-models/images/tall_skyscrapers_1.png',
        model_url:'/static/3d-models/glbs/tall_skyscrapers_1.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10022,
        nameCn:'摩天大楼Ⅱ型',
        nameEn:'tall_skyscrapers_2',
        head_url:'/static/3d-models/images/tall_skyscrapers_2.png',
        model_url:'/static/3d-models/glbs/tall_skyscrapers_2.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10023,
        nameCn:'摩天大楼Ⅲ型',
        nameEn:'tall_skyscrapers_3',
        head_url:'/static/3d-models/images/tall_skyscrapers_3.png',
        model_url:'/static/3d-models/glbs/tall_skyscrapers_3.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10024,
        nameCn:'摩天大楼Ⅳ型',
        nameEn:'tall_skyscrapers_4',
        head_url:'/static/3d-models/images/tall_skyscrapers_4.png',
        model_url:'/static/3d-models/glbs/tall_skyscrapers_4.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    },
    {
        id:10025,
        nameCn:'摩天大楼Ⅴ型',
        nameEn:'tall_skyscrapers_5',
        head_url:'/static/3d-models/images/tall_skyscrapers_5.png',
        model_url:'/static/3d-models/glbs/tall_skyscrapers_5.glb',
        center:{x:0,y:0},
        use:[],
        entity:null
    }
]
*/